### PR TITLE
Fix replace operator handling

### PR DESCRIPTION
**Pull request by mikroskeem**
This PR addresses two issues:
1) Misleading log message - saying that download succeeded and then failing immediately after it isn't... nice.
2) #22

### CODE REVIEW

**Comment by mikroskeem** [comment]
Though seems like I overlooked one simple detail: replacing the actual repository. Thus this PR cannot be considered ready right now, as it only handles version replacing right now...

**Comment by mikroskeem** [comment]
If someone could provide a proper working example for repository replacement, then that would help a lot.

**Comment by danderson** [comment]
One example of a Go project that vgo2nix currently fails on (I think because of replace handling), is https://github.com/coredns/coredns . I've been trying to use vgo2nix to update the package to v1.6.5, but vgo chokes with:

```
[...]
Fetching github.com/Azure/go-autorest
panic: Error processing import path "github.com/Azure/go-autorest/autorest": exit status 1

goroutine 1 [running]:
main.main()
	/home/dave/hack/homelab/nix/cdns/coredns/vgo2nix/main.go:248 +0x71a
```

That module is one that is being replaced in go.mod:

```
replace (
	github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.0.0+incompatible
	github.com/miekg/dns v1.1.3 => github.com/miekg/dns v1.1.22
)
```

I tried using vgo2nix patched with this PR, but as you predicted, the failure is the same.

**Comment by SuperSandro2000** [comment]
This got implemented with 6b8cbc72ab4542bba09ef790dabaed5a95b52004.

@Mic92 I think this can be closed.

**Pull request closed without merging**
